/*
 * Copyright (c) 2024 Niklas Oberhuber
 * SPDX-License-Identifier: Apache-2.0
 */

`default_nettype none

/*
 * 8-bit Prime Number Detector
 *
 * Set the 8 DIP switches to any number 0–255.
 * The 7-segment display shows the lower hex nibble of the number (0–F).
 * The decimal point lights up when the number is prime.
 *
 * There are 54 primes in the range 0–255:
 *   2, 3, 5, 7, 11, 13, ... 241, 251
 *
 * Hardware mapping:
 *   ui_in[7:0]  = number to test (8 DIP switches)
 *   uo_out[6:0] = 7-segment display: lower nibble as hex digit 0–F
 *   uo_out[7]   = decimal point: 1 if prime, 0 if not
 */
module tt_um_obrhubr (
    input  wire [7:0] ui_in,    // Dedicated inputs
    output wire [7:0] uo_out,   // Dedicated outputs
    input  wire [7:0] uio_in,   // IOs: Input path
    output wire [7:0] uio_out,  // IOs: Output path
    output wire [7:0] uio_oe,   // IOs: Enable path (active high: 0=input, 1=output)
    input  wire       ena,      // always 1 when the design is powered, so you can ignore it
    input  wire       clk,      // clock
    input  wire       rst_n     // reset_n - low to reset
);

  // -------------------------------------------------------------------------
  // IS_PRIME[255:0]: bit i is 1 if i is a prime number.
  // Covers all 54 primes in the range 0–255.
  // Generated by: python3 -c "
  //   s=set()
  //   [s.add(n) for n in range(2,256) if all(n%i for i in range(2,int(n**.5)+1))]
  //   print(hex(sum(1<<i for i in s)))"
  // -------------------------------------------------------------------------
  localparam [255:0] IS_PRIME =
    256'h08028228800800A28028208820A00A08800228A20208828828208A20A08A28AC;

  // -------------------------------------------------------------------------
  // Decimal point: lights up when the input number is prime
  // -------------------------------------------------------------------------
  assign uo_out[7] = IS_PRIME[ui_in];

  // -------------------------------------------------------------------------
  // 7-segment hex decoder: display lower nibble of input as 0–F
  //
  // Segment mapping:  uo_out[0]=a  uo_out[1]=b  uo_out[2]=c  uo_out[3]=d
  //                   uo_out[4]=e  uo_out[5]=f  uo_out[6]=g
  //
  //    aaa
  //   f   b
  //   f   b
  //    ggg
  //   e   c
  //   e   c
  //    ddd
  // -------------------------------------------------------------------------
  reg [6:0] seg;
  always @(*) begin
    case (ui_in[3:0])
      4'h0: seg = 7'h3F; // 0: a b c d e f
      4'h1: seg = 7'h06; // 1: b c
      4'h2: seg = 7'h5B; // 2: a b d e g
      4'h3: seg = 7'h4F; // 3: a b c d g
      4'h4: seg = 7'h66; // 4: b c f g
      4'h5: seg = 7'h6D; // 5: a c d f g
      4'h6: seg = 7'h7D; // 6: a c d e f g
      4'h7: seg = 7'h07; // 7: a b c
      4'h8: seg = 7'h7F; // 8: a b c d e f g
      4'h9: seg = 7'h6F; // 9: a b c d f g
      4'hA: seg = 7'h77; // A: a b c e f g
      4'hB: seg = 7'h7C; // b: c d e f g
      4'hC: seg = 7'h39; // C: a d e f
      4'hD: seg = 7'h5E; // d: b c d e g
      4'hE: seg = 7'h79; // E: a d e f g
      4'hF: seg = 7'h71; // F: a e f g
    endcase
  end
  assign uo_out[6:0] = seg;

  assign uio_out = 8'b0;
  assign uio_oe  = 8'b0;

  // Suppress unused input warnings (purely combinational, no clk/rst needed)
  wire _unused = &{ena, clk, rst_n, uio_in, 1'b0};

endmodule
